---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-controller
  labels:
    clusterops.io/release: "devel"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-controller
  template:
    metadata:
      labels:
        app: label-controller
        clusterops.io/release: "devel"
    spec:
      serviceAccountName: clusterops
      containers:
        - name: controller
          image: ko://github.com/ab-ghosh/knative-controller/cmd/labeler
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace